README.md
Added a new entry to study and education section
=> added new entry to study section

README.md
a few apps that I find useful.
=> added from bookmarks

README.md
High Quality youtube to mp3 converter
=> Added vubey

README.md
If you are adding something, explain briefly why do you think that web app is **awesome**.
If you are changing something, explain briefly why that change was needed.
Apart from that, go through the following checkpoints --
for this project.
=> Added Superbetize

README.md
If you are adding something, explain briefly why do you think that web app is **awesome**.
If you are changing something, explain briefly why that change was needed.
Apart from that, go through the following checkpoints --
for this project.
=> added new entry to IDEs section

README.md
**[https://www.seedr.cc/]**
**[Cloud based Torrent Downloader that can download multiple torrent files in a day of total size of 2 GB on free account. 500 MB increase on contributing a new user from your shared link]**
=> added seedr

README.md
If you are adding something, explain briefly why do you think that web app is **awesome**.
If you are changing something, explain briefly why that change was needed.
Apart from that, go through the following checkpoints --
for this project. 
Vdeotoolbox is a free video editor with easy to use interface and good features.
=> added new entry to audio and video section

README.md
**[https://muki.io]**
**[It's an online music player for rare formats, and it includes a handpicked collection of video game music. Kind of like a Spotify for MIDI and chiptunes, but no account required.]**
=> Add Muki.io, online music player for sequenced music. No login required.

README.md
Fuge.it is a web-based torrent client and cyberlocker storage service that allows you to upload and download files using only your web browser. Easily share your torrent transfers and files with friends.
=> added new entry to Internet Downloaders section

README.md
http://sqlfiddle.com/
A tool for easy online testing and sharing of database problems and their solutions. You can check your schema and SQL queries without setting up the database for yourself. It supports `MySQL 5.5`, `MySQL5.6`, `Oracle 11g R2`, `PostgreSQL 9.3`, `SQLite` (`WebSQL` and `SQL.js`), `MS SQL Server` (2014 and 2008). And on the top of all of that, it also provides you a section called `View Execution Plan` where you can see the task associated with sub operations for a query and flow of control.
=> Added SQLFiddle

README.md
**http://www.jango.com/**
**Free internet radio. Listen to hundreds of genre stations or create your own with your favorite music. Awesome online radio with no hassle, just start a station and listen to your heart's content. Login is not mandatory but if you make an account too, no junk mail is sent by them.**
=> Add Jango Radio

README.md
**http://musicpleer.cc/**
**Stream or download your favourite songs without any hassle**
**http://direct-torrents.com/**
**Size limit of 10GB and a comfortable bandwidth**
=> Add MusicPleer and Direct Torrents

README.md
**Irrelevant - correcting typos**
**These are some corrections to typos.**
=> Some grammar corrections

README.md
**http://rollapp.com**
**Unique, can run any windows/linux app in browser**
**http://realtimeboard.com**
**Best collaborative drawing I've used with lots of features**
**http://ezgif.com**
**Manipulating gif files with lots of possiblities**
**https://color.adobe.com/**
**Color scheme designer, useful for UX/UI development**
**http://isup.me/**
**Useful for diagnosing network problems**
**http://wordsafety.com/**
**To avoid using words that might be offensive or inappropriate in international communities**
=> Add rollApp, RealtimeBoard, ezGIF, Color CC, isup.me and WordSafety.

README.md
**https://awwapp.com/**
It's a real-time collaborative web whiteboard. One can use it without logging in or creating an account. Even the collaborative feature works without an user account.
Also it is very popular in classroom environments and often one the first result on google when searching for *web whiteboard* or *online whiteboard*.
=> add awwapp.com

README.md
[imgh.us/](https://imgh.us/)
It is an Image hosting service that let's us host images of maximum size 16MB of various file types.
=> Added imgh.us

README.md
https://snapdrop.net/
Open source local file sharing inspired by Apple's Airdrop.
It should be included because it's really neat and useful to share file directly with other people on the same lan. It works mostly client-side, is open source and can be self-hosted too.
- [x ] I have read the [Contribution guidelines](https://github.com/aviaryan/awesome-no-login-web-apps/blob/master/CONTRIBUTING.md) and I am confident that my PR is suitable. 
- [ x] This pull request has a descriptive title. For example, `Add [App name]`, not …
=> Add Snapdrop to "File Hosting/Sharing"

README.md
**http://multcloud.com/home**
**Multcloud is a free service, helps to manage multiple cloud accounts, you can manage, move, copy and migrate files between cloud services. Supports all cloud services. 2 TB of cloud storage for free on Multicloud. Supports downloading large files (no speed/size limit).**
=> Added MultCloud

README.md
**https://web-capture.net/**
**Want to capture a full web page screenshot? Submit your link, convert it to JPG, PDF, or whatever, online! You will also have the opportunity to download the picture as a ZIP file.**
=> Add web-capture

README.md
**http://unfurlr.com/**
**Uncover the original link hiding behind the shortened link.**
=> Add unfurlr

README.md
**http://www.iconfinder.com/**
**Download icons in popular formats and sizes.**
=> Add Iconfinder

README.md
**http://www.printwhatyoulike.com/**
**print web pages without the clutter or save them as PDF or HTML.**
=> Add PrintWhatYouLike

README.md
**http://www.pdfescape.com**
**Edit or create PDFs in browser itself at ease.**
=> Add pdfescape

README.md
**http://scr.im/**
**Share your email freely online without worrying about spam, this webapp will give you an alternate link of your email using which original email can be reached.**
=> Add scr.im

README.md
**http://www.followupthen.com/**
**Setup email reminders conveniently.**
=> Add followupthen

README.md
**http://www.myfonts.com/WhatTheFont/**
**Curious about font used in any image ? This utility can come in handy. Upload any image and determine the font used(closest),**
=> Add WhatTheFont

README.md
**https://www.onlineocr.net/**
**Convert a scanned PDF into doc, xls or txt through text detection.**
=> Add OnlineOCR

README.md
**http://www.polishmywriting.com/**
**Get a feedback on your writing, find grammatical errors, suggestions etc.**
=> Add PolishMyWriting

README.md
**https://gtmetrix.com/**
**This web-app gives you insight on how well your site loads and provides actionable recommendations on how to optimize it.**
=> Add GTmetrix

README.md
**http://www.similarsites.com/**
**Find websites similar to the one you enter.**
=> Add  SimilarSites

README.md
**https://www.noteflight.com/login**
**Print music sheets, write your own music online (review).**
=> Add NoteFlight

README.md
**http://www.google.com/webfonts**
**A cool collection of opne-source fonts by google for your webapps or to be downloaded for offline use.**
=> Add Google Fonts

README.md
**http://exif.regex.info/exif.cgi**
**View hidden data of an image stored in the image(EXIF format).**
=> Add Metadata Viewer

README.md
**http://www.wordle.net/**
**Wordle is a toy for generating “word clouds” from text that you provide. The clouds give greater prominence to words that appear more frequently in the source text. You can tweak your clouds with different fonts, layouts, and color schemes.**
=> Add Wordle

README.md
**http://lmgtfy.com/**
**When your friends are too lazy to use Google on their own, troll them with this.**
=> Add lmgtfy

README.md
Fixes #57 
**http://play.typeracer.com**
**Feeling proud to introduce a new category, Games !**
**Evaluate your typing speed while competing against others.**
=> Add Games category

README.md
**http://faxzero.com/**
**Send an online fax for free.**
=> Add faxzero

README.md
**http://www.whoishostingthis.com/**
**Find the web host of any website.**
=> Add WhoIsHostingThis

README.md
**http://scribblemaps.com/**
**Create custom google maps at ease, account needed to save these custom maps into your profile.**
=> Add ScribbleMaps

README.md
**http://disposablewebpage.com/ `[Account]`**
**Create a temporary web page that self-destructs.**
=> Add disposableWebPage

README.md
Reverts aviaryan/awesome-no-login-web-apps#76
=> Revert "Add disposableWebPage"

README.md
**http://aviaryan.in/mAhLyfeMahRulezz/**
**dA aNn0Y1Ng t3Xt g3NeRa7or (The annoying text generator :-P).**
=> Add Annoying-Text-Gen

README.md
=> Update link of Musicpleer

README.md
**https://www.typing.com/student/start**
Fixes #80 
**Master touch-typing at ease. Go through the predefined typing courses and accumulate badges and track progress by creating an account.**
=> Add TypingWeb

README.md
**https://www.protectedtext.com/**
**This online notepad is completely encrypted. Adding this to the list provides an alternative to the other notepads because it is ad-free and does not use sessions or cookies.**
=> Add ProtectedText

README.md
Fixed #82
[http://acronymcreator.net/](http://acronymcreator.net/)
This web-app generates acronym for anything - project, organization, etc having at least two words.
=> Add AcronymCreator

README.md
**http://www.talltweets.com/**
**Send tweets longer than 140 characters.**
=> Added talltweets

README.md
Fixed #96 
**http://studio.stupeflix.com/**
**Make a movie out of your images, audio and video clips.**
=> Added Stupeflix [Account]

README.md
Fixed #92 
**http://builtwith.com/**
**Find the technology stack to know everything about a website.**
=> Added buildwith

README.md
Fixes #103 
**https://www.choosemypc.net**
**Search for the best combination of parts considering your requirements for your PC under a given budget.**
=> Add ChooseMyPC

README.md
Fixes #102 
**www.invoicetome.com**
**Generate professional invoices from various templates with your company details.**
=> Add InvoiceToMe

README.md
Fixes #93 
**www.woorank.com**
**SEO Audit tool and website review which provides with global and local rank in terms of traffic generated.**
=> Add Woorank

README.md
Fixed #84 
**https://ifttt.com/**
**Create a connection between your favourite online services. For example, if you want to post the same content on several social networking sites at a time IFTTT can come in handy. 
Triggers are the "this" part of an applet. They are the items that "trigger" the action. For example, from an RSS feed, you can receive a notification based on a keyword or phrase. Actions are the "that" part of an applet. They are the output that results from the input of the trigger. If you "like" a picture in Instagram (trigger), an IFTTT app can send the photo to your Dropbox account (action).**
=> Added IFTTT

README.md
Fixes #115 
**https://www.pdfescape.com/**
**This app is already in the list updated dead link to live one**
=> [Fix] Deadlink of PdfEscape

README.md
Fixes #118 
**http://fuge.it/howitworks**
**Link Fixes**
=> [Fix] Privacy Error in Link 

README.md
Fixes #105 
**http://postfity.com/**
**Schedule posts on Facebook, Twitter & LinkedIn.**
=> Added Postify

README.md
Fixes #104 
**https://gifdeck.in**
**Convert slides from slideshare to gif.**
=> Added gifdeck

README.md
Fixes #114 
**https://10minutemail.com/**
**A temporary fully functional email address for 10 minutes.**
=> Add 10MinuteMail

README.md
Fixes #106 
**https://burner.bonanza.com/**
**Tool to burn/remove the background of  an image and instantly share on Facebook or Twitter, login to download the edited image as PNG or JPEG.**
=> Added Burner Bonanza [Account]

README.md
Fixes #117 
**http://fatiherikli.github.io/brainfuck-visualizer**
**Javascript Brainfuck Interpreter + Visualizer**
=> Add Brainfuck Visualizer

README.md
**Added some valuable piece of information to the description of 10MinuteMail.**
=> Updated 10MinuteMail description

README.md
**Added a space between content and parenthesis.**
=> Updated web-capture desc

README.md
**Added a space between content and parenthesis.**
=> Updated Image-Metadata-Viewer desc

README.md
Fixes #128 
**http://wrd.bih.nic.in/font_KtoU.htm**
**Convert Krutidev to Unicode (Mangal) and vice versa in one click.**
=> Add Krutidev to Unicode Converter

README.md
**http://codepad.org/**
**An online IDE which is similar to Ideone but is older than that**
=> Add codepad to Programming Editors and IDEs

README.md
Fixes #125 
**Sorted the list as suggested**
=> Sorted according to Title

README.md
Fixed #133 
**http://www.favicon-generator.org/**
**Tool useful for generating favicons for  your web-apps or App  Icons for your favourite Android or  iOS apps by uploading your favourite image.**
=> Added favicon-genereator

README.md
Fixed #140 
**http://www.cssmenumaker.com/**
**This generator is great for when you just need a quick, simple drop-down menu. Just choose a style, create your menu items, and download the respective CSS for your desired menu.**
=> Added CSS Menu Maker

README.md
Fixed #139 
**http://bgpatterns.com/**
**BgPatterns is possibly the most powerful repeating pattern creator online. You can choose from a variety of shapes and then customize size, rotation, placement, color, texture, and more.**
=> Added BG Patterns

README.md
Fixed #138 
**http://csstypeset.com/**
**CSS Type Set lets you create typography designs and generates the CSS for you. Just paste in text you want to modify, and then use the options at the bottom to customize it and it will generate the CSS in real-time.**
=> Added CSS Typeset

README.md
http://browserpad.org/
**[A server-less plain text editor in the browser.]**
=> Add Browserpad

README.md
**https://www.chess.com/**
**Common web-app to play chess. Learn to play chess online else play with over 15 million users around the globe or against AI with various difficulty levels.**
=> Added CHESS in games list

README.md
**http://bugmenot.com/**
**BugMeNot is a helpful platform for finding and sharing logins. It helps when you want to be anonymous or don't want to make account.**
=> Add BugMeNot

README.md
**https://icomoon.io/app**
**IcoMoon is an icon solution, providing three main services: Vector Icon Packs, The IcoMoon App, and hosting icons as SVGs or fonts.**
=> Add IcoMoon

README.md
**https://autoprefixer.github.io/**
Fixed #157 
**A postprocessor for handling vendor prefixes in CSS. Just paste the regular CSS and get the vendor handled added CSS instantly for easy cross-browser support.**
=> Add CSS Autoprefixer

README.md
http://www.writeurl.com/
**A collaborative real-time online text editor.No registration. No password. Just click new document.**
=> Online text editor with  collaboration 

README.md
**https://ongaku.js.org/**
**Online Anime Radio**
=> Add ongaku

README.md
**Fuge.it**
Fixes #169 
**This is about removing this app from list**
=> Removed Fuge.it

README.md
**http://snapdrop.net/**
Fixes #167 
**This is about SSL link fix and this also fixes Travis Build**
=> SnapDrop Link Fixed

README.md
**http://openings.moe/**
Fixes #170 
**Free anime radio, listen or download anime openings and endings without any hassle.**
=> Add animeopenings

README.md
Fixes #173 
**[Flaming Text](http://flamingtext.com/)**
**This app helps us create or generate logo for anything, we can modify and download in many formats**
=> Added Flaming text 

README.md
**https://alarmdj.com**
**Alarm DJ is an online alarm clock that plays your MP3 files and YouTube videos of your choice as alarm sound.**
=> Add alarmdj.com under Miscellaneous category

README.md
**https://resume-nation.github.io**
**This is an open source resume builder progressive web app. It fulfils the purpose of this list i.e it works without any sort of registration. In fact, it can be used as a standalone app offline as well.**
=> Add Resume Nation

README.md
**https://www.taskade.com**
**Taskade is a simple and collaborative editor for making notes, task lists, and outlines. It does not require registration and can be shared using an instant share link.**
Please consider including Taskade. Thanks!
Sign up is optional. Users can instantly create a task list via Taskade and share the link to collaborate with others.
=> Add Taskade

README.md
**http://radio.garden/**
**This webapp provides users with the intuitive feature to select a marked city in the whole world and select from the radio stations available there.**
=> Add Radio Garden

README.md
**http://telegra.ph/**
**This app allows anyone to publish richly formatted text posts to the web. It should be included in this list because there are not many websites that allow people to publish typographically beautiful articles without creating an account.**
=> Add Telegraph

README.md
Closes https://github.com/aviaryan/awesome-no-login-web-apps/issues/186
=> Remove ascii.li

README.md
**http://www.cssmatic.com/**
Fixes #159 
**Ultimate CSS tools for web developers.**
=> Added CSSmatic

README.md
Fixes #177 #190 
**https://www.diffnow.com/**
**Advanced, online and free File Difference checking, with options like Upload file, compare files by their links or Text Input.**
=> Added DiffNow

README.md
**https://stackedit.io/**
**Rich in-browser markdown editor that works offline.**
**https://dailytodo.org/**
**Simple todo list maker.**
=> add StackEdit.io, Daily Todo, Polls.io

README.md
**Website:** https://www.jsonstore.io/
**Description:** 
jsonstore.io offers a free, secured and JSON based cloud datastore for small projects. You just enter https://www.jsonstore.io/, copy the URL and start sending HTTP requests to communicate with your datastore.
=> Add jsonstore.io

README.md
**https://write.as**
**Write.as is similar to Telegraph, but lets you see past posts you've made, and edit or delete them all without signing up. Its Android, iOS, Chrome OS, command-line apps and Chrome extension all work without signing up.**
=> Add Write.as

README.md
**https://sketch.io/sketchpad/**
**Sketchpad is a free online application to create digital artwork and export to popular image formats JPEG, PNG, SVG, and PDF. It fulfils the purpose of this list i.e it works without any sort of registration.**
=> Add sketchpad

README.md
**https://www.flaticon.com/**
**Flaticon is the largest search engine of free icons in the world. It fulfils the purpose of this list i.e it works without any sort of registration. This PR is for issue #192**
=> Add Flaticon to Search Engines

README.md
Here is my PR to remove youtubemp3.to. Please let me know if there's anything else I should do.
=> Remove youtubemp3.to as it no longer works

README.md
**http://pythontutor.com/visualize.html#mode=edit**
**PythonTutor helps people overcome a fundamental barrier to learning programming: understanding what happens as the computer executes each line of a program's source code. Using this tool, you can write Python, Java, JavaScript, TypeScript, Ruby, C, and C++ programs in your Web browser and visualize what the computer is doing step-by-step as it executes those programs. It also fulfills the purpose of this list i.e it works without any sort of registration.**
=> Add PythonTutor

README.md
**https://edubirdie.com/plagiarism-checker**
**Edubirdie is a free online plagiarism checker which gives percentage of similarity comparing our content with online resources.**
=> Add entry for edubirdie

README.md
**[http://jsonviewer.stack.hu/]**
**[This is a great tool to view any json data in human readable form. Great for people who create apis and deal with nested json]**
**[http://www.mailinator.com/]**
**[Mailinator is a disposable email service. It is great for developers who want to test their email sending functionality or for quick signup without using your primary email. ]**
=> JsonViewer and mailinator added

README.md
http://www.objgen.com/
This live code generator helps you generate code(JSON, HTML etc.) in real time as you type in only the key words, types and properties using a text based syntax. Really increases productivity when a large amount of similar code has to be written, it allows the user to type in only the important components, and takes care of the code syntax. Code generation is live. 
=> Add ObjGen to programming tools

README.md
https://www.photopea.com/
Photoshop alternative, developed by a single developer. More info https://www.reddit.com/r/IAmA/comments/9urjmg/i_made_a_free_alternative_to_photoshop_that_is/
=> Add PhotoPea to graphics as a Photoshop alternative

README.md
**https://hackmd.io**
**Online markdown editor that allows for collaboration and live previewing. Powerful features include drag and drop images, MathJax & UML, and slide mode. Allows easy exporting to HTML, PDF, MD**
=> Add HackMD

README.md
**[https://hardbin.com/]**
**[Secure encrypted pastebin hosted on IPFS.]**
- [x ] I have read the [Contribution guidelines](https://github.com/aviaryan/awesome-no-login-web-apps/blob/master/CONTRIBUTING.md) and I am confident that my PR is suitable. 
- [ x] This pull request has a descriptive title. For example, `Add [App name]`, not `Update readme.md` or `Added new entries`.
- [x ] The app I added is not a duplicate.
=> Added hardbin to security 

README.md
Added app to "File Hosting/Sharing" section.
**https://send.firefox.com**
**Free filesharing utility from mozilla**
1gb without an account allowed, 2.5gb with account. Password protection + expiry included free
=> Add Firefox-Send

README.md
**https://leanlogomaker.com**
**This simple tool lets startup founders generate a set of professional looking logos, covers and profile images that can be used on their social media sites without spending too much time.**
=> Add LeanLogoMaker

README.md
**Doka.photo**
**Super simple and handy image editor, no account required.**
=> Add Doka.photo to Graphics, Images and Design

README.md, test.sh
=> remove dead links

README.md
**[agar.io , paper-io.com , diep.io]**
**[These are 3 little game online that are fun to play, no login is required]**
-  [X] I have read the [Contribution guidelines](https://github.com/aviaryan/awesome-no-login-web-apps/blob/master/CONTRIBUTING.md) and I am confident that my PR is suitable.
=> Added agar.io , paper-io.com , diep.io

README.md
**https://morsify.net**
**Morsify is an easy to use, [open source](https://github.com/ozdemirburak/morsify) Morse code translator. With Morsify, one can translate Morse code to text and text to Morse code, plus, can play the sound of the Morse code.**
=> Added Morsify, a Morse Code Translator to Misc.

README.md
**https://matthewmiller.dev/experiments/emojify/**
**This app is a simple web tool to spice up text, lyrics, or poems by adding emojis. I feel it should be added as there is nothing else like this on the list, and it fits the requirement of the list (not requiring a login).**
=> Add Emojify

README.md
https://appear.in has rebranded to https://whereby.com so this PR will update it
=> UPDATE: appear.in to whereby.com

README.md
https://doonline.cc/video-downloader-converter.html 
Internet video and audio downloader without any accounts, we also aim for minimal amount of ads to provide better experience to users
=> Add dOnline Internet downloader add, delete vubey.yt - website not available anymore

README.md
**https://jspaint.app**
**JSPaint is a near-pixel-perfect copy of MSPaint developed from scratch in Javascript. My brother built this app and it's amazing. I use it all the time for basic things like cropping and annotating screenshots. Besides its nostalgia vibe, it also has some fun hidden features for making .gif animations and real-time collaborative drawing.  
Here is the github page: https://github.com/1j01/jspaint**
=> Add JSPaint to drawing app section

README.md
**https://www.nitrome.com/**
**Collection of free pixelart games that can be played without giving your email. Fresh isn't required for everygame so it's a good alternative for miniclip..**
=> Add nitrome

README.md
**https://www.piskelapp.com/**
**Piskel is a free online editor for animated sprites & pixel art. It's a great tool for creating and editing sprite atlases for games or gifs.**
=> Add Piskel

README.md
https://www.ambient-mixer.com/
**Listen to free audio atmospheres (e.g. Scottish Rain/Slytherin Common Room) or mix your own ambient sound online.**
https://skribbl.io/
**Several players connect to a lobby and one of them is given a word that they need to draw without saying what it is while the others have to identify it.**
https://surviv.io/
**Surviv.io is a 2D battle royale game. You only have one live per game, no respawn.**
https://csacademy.com/app/graph_editor/
**Draw directed graph systems with and without edge values and physics.**
(Similar to the "Directed Graph Editor", but with the additional possibility to assign values to the edges.)
Failure to properly do so will just result in the pull request being closed and everyone's time wasted. Please read it twice. Most people miss …
=> Add [Ambient Mixer, Skribbl.io, Surviv.io]

README.md
**https://vocalremover.org/**
**Separate voice from music out of a song with artificial intelligence. Free. No registration. No ads.**
=> Add vocalremover.org

README.md
Add a2fax.com
**https://www.a2fax.com**
**a2fax is a free online fax service. Unlike the other fax service detailed. a2fax doesn't place ads on faxes and allows users to add their own custom logos to faxes.**
=> Add a2fax.com

README.md
**https://randommer.io/**
**It provides useful data for programmers and also validates this data to ensure that is correct.**
=> Add Randommer

README.md
**[cleanicons.xyz](https://cleanicons.xyz)**
**An easy to use tool to download Font Awesome glyphs as PNG's in any size or color.**
=> Added Cleanicons.xyz

README.md
**https://writexo.com**
**Online private notepad allows you to save your text in the cloud.**
=> Add WriteXO

README.md
https://freetools.site/
freetools.site is a website where you can find a variety of free software (quick-use tools) to make everyday tasks easier. This website can be used by anyone, it is especially aimed at people without special IT skills. The tasks performed on a website can be very diverse: compressing files, changing file formats, improving image quality, creating animation, shortening audio or video, amplifying, and so on.
=> Add freetools.site

README.md
**https://cryptii.com/**
**This web app offers modular conversion, encoding and encryption with a wide variety of ciphers and methods. The interface is intuitive for both beginners and professionals.**
=> Add Cryptii

README.md
**https://abc-map.fr**
**This is about geographical maps, it is easy to use and to understand, it is free software (GNU GPLv3), and has no concurrent in your list.**
(Thanks for your list guys, it is very useful)
=> Add Abc-map

README.md
**[Bucket Listy](https://bucketlisty.com/) 
Bucket list manager with unique ideas where you can add your own.**
=> Add Bucket Listy

README.md
**https://gidd.io**
**Its a free gaming platform with several minigames like Yatzy, Crazy Eights, Categories and GeoGuess. Work on all devices and can be played with friends.**
- [ x] I have read the [Contribution guidelines](https://github.com/aviaryan/awesome-no-login-web-apps/blob/master/CONTRIBUTING.md) and I am confident that my PR is suitable. 
- [x ] This pull request has a descriptive title. For example, `Add [App name]`, not `Update readme.md` or `Added new entries`.
- [ x] The app I added is not a duplicate.
=> Add Gidd.io

README.md
**https://branition.com/colors**
**Hand-curated collection of color pallets best fitted for branding.**
=> Add Branition Colors

README.md
**https://keepformula.github.io/**
**Keep Formula is a simple app to make your calculations easier, no login, also it's open source. you can find it [here](https://keepformula.github.io/)**
=> fix keepformula address

README.md
https://pixelcraft.web.app
https://github.com/rgab1508/PixelCraft
A pixel Art & Animation Creation Tool Built using HTML5 Canvas.
It is a Progressive Web App (PWA) with offline compatibility.
It is mobile-friendly and is very easy to use.
=> Add PixelCraft

README.md
**https://goteam.video/**
**GoTeam is a tool made by folks at Lookback.io:**
**- Has (free) end-to-end encryption**
**- It was launched and used by a huge group of people at the UXR Collective Conference in June 2020.**
**- It has two reactions: ❤️  with the 1️⃣  key and 👎  with the 9️⃣  key**
=> Add GoTeam

README.md
New version of original (already approved) PR (https://github.com/aviaryan/awesome-no-login-web-apps/pull/222)
- App: [youtube.ndo.dev](https://youtube.ndo.dev/)
- Repo: [ndom91/youtube-playlists](https://github.com/ndom91/youtube-playlists)
Disclaimer: this app is a sideproject of mine
However, it is a web app that does not require an account, and does what it says on the tin.
The user can either drag and drop youtube urls onto the page, or it will recognize youtube URLs in the clipboard, and create dynamic playlists. That way you dont have to junk up your youtube account with all sorts of throw-away playlists.
=> Add "Youtube Dynamic Playlists" (2)

README.md
**https://sharesnip.rosano.ca**
**A QR code scanner and generator that works offline without login**
=> Add Sharesnip
